#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 157
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13

enum {
  sym__ident_lower = 1,
  anon_sym_EQ = 2,
  anon_sym_POUND_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_COLON_COLON = 6,
  sym__ident_upper = 7,
  anon_sym_import = 8,
  anon_sym_as = 9,
  anon_sym_extern = 10,
  anon_sym_function = 11,
  anon_sym_LPAREN = 12,
  anon_sym_COLON = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  sym__item_relation = 17,
  sym_item_rule = 18,
  sym_item_typedef = 19,
  sym_literal_bool_false = 20,
  sym_literal_bool_true = 21,
  sym_literal_int = 22,
  anon_sym_LBRACK = 23,
  anon_sym_DASH_GT = 24,
  sym_literal_string = 25,
  sym_name_var_type = 26,
  anon_sym_DOT = 27,
  anon_sym_var = 28,
  anon_sym__ = 29,
  sym_term_break = 30,
  anon_sym_if = 31,
  anon_sym_else = 32,
  sym_term_continue = 33,
  anon_sym_for = 34,
  anon_sym_in = 35,
  anon_sym_match = 36,
  anon_sym_return = 37,
  sym_type_spec_simple = 38,
  sym_ROOT = 39,
  sym_annotated_item = 40,
  sym_attribute = 41,
  sym_attributes = 42,
  sym__expr = 43,
  sym__ident = 44,
  sym__ident_lower_scoped = 45,
  sym_ident_scope = 46,
  sym_item = 47,
  sym_item_import = 48,
  sym__item_function = 49,
  sym_item_function_extern = 50,
  sym_item_function_normal = 51,
  sym__literal_bool = 52,
  sym_literal_map = 53,
  sym_literal_vec = 54,
  sym_module_alias = 55,
  sym_module_path = 56,
  sym_name = 57,
  sym_name_arg = 58,
  sym_name_func = 59,
  sym_name_var_term = 60,
  sym__term = 61,
  sym_term_cond = 62,
  sym_term_decl_var = 63,
  sym_term_for = 64,
  sym__term_literal = 65,
  sym_term_return = 66,
  sym_term_wildcard = 67,
  aux_sym_ROOT_repeat1 = 68,
  aux_sym_attributes_repeat1 = 69,
  aux_sym_ident_scope_repeat1 = 70,
  aux_sym_item_function_extern_repeat1 = 71,
  aux_sym_literal_map_repeat1 = 72,
  aux_sym_literal_vec_repeat1 = 73,
  aux_sym_module_path_repeat1 = 74,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__ident_lower] = "_ident_lower",
  [anon_sym_EQ] = "=",
  [anon_sym_POUND_LBRACK] = "#[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_COLON] = "::",
  [sym__ident_upper] = "_ident_upper",
  [anon_sym_import] = "import",
  [anon_sym_as] = "as",
  [anon_sym_extern] = "extern",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__item_relation] = "_item_relation",
  [sym_item_rule] = "item_rule",
  [sym_item_typedef] = "item_typedef",
  [sym_literal_bool_false] = "literal_bool_false",
  [sym_literal_bool_true] = "literal_bool_true",
  [sym_literal_int] = "literal_int",
  [anon_sym_LBRACK] = "[",
  [anon_sym_DASH_GT] = "->",
  [sym_literal_string] = "literal_string",
  [sym_name_var_type] = "name_var_type",
  [anon_sym_DOT] = ".",
  [anon_sym_var] = "var",
  [anon_sym__] = "_",
  [sym_term_break] = "term_break",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [sym_term_continue] = "term_continue",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_match] = "match",
  [anon_sym_return] = "return",
  [sym_type_spec_simple] = "type_spec_simple",
  [sym_ROOT] = "ROOT",
  [sym_annotated_item] = "annotated_item",
  [sym_attribute] = "attribute",
  [sym_attributes] = "attributes",
  [sym__expr] = "_expr",
  [sym__ident] = "_ident",
  [sym__ident_lower_scoped] = "_ident_lower_scoped",
  [sym_ident_scope] = "ident_scope",
  [sym_item] = "item",
  [sym_item_import] = "item_import",
  [sym__item_function] = "_item_function",
  [sym_item_function_extern] = "item_function_extern",
  [sym_item_function_normal] = "item_function_normal",
  [sym__literal_bool] = "_literal_bool",
  [sym_literal_map] = "literal_map",
  [sym_literal_vec] = "literal_vec",
  [sym_module_alias] = "module_alias",
  [sym_module_path] = "module_path",
  [sym_name] = "name",
  [sym_name_arg] = "name_arg",
  [sym_name_func] = "name_func",
  [sym_name_var_term] = "name_var_term",
  [sym__term] = "_term",
  [sym_term_cond] = "term_cond",
  [sym_term_decl_var] = "term_decl_var",
  [sym_term_for] = "term_for",
  [sym__term_literal] = "_term_literal",
  [sym_term_return] = "term_return",
  [sym_term_wildcard] = "term_wildcard",
  [aux_sym_ROOT_repeat1] = "ROOT_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
  [aux_sym_ident_scope_repeat1] = "ident_scope_repeat1",
  [aux_sym_item_function_extern_repeat1] = "item_function_extern_repeat1",
  [aux_sym_literal_map_repeat1] = "literal_map_repeat1",
  [aux_sym_literal_vec_repeat1] = "literal_vec_repeat1",
  [aux_sym_module_path_repeat1] = "module_path_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__ident_lower] = sym__ident_lower,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_POUND_LBRACK] = anon_sym_POUND_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym__ident_upper] = sym__ident_upper,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__item_relation] = sym__item_relation,
  [sym_item_rule] = sym_item_rule,
  [sym_item_typedef] = sym_item_typedef,
  [sym_literal_bool_false] = sym_literal_bool_false,
  [sym_literal_bool_true] = sym_literal_bool_true,
  [sym_literal_int] = sym_literal_int,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_literal_string] = sym_literal_string,
  [sym_name_var_type] = sym_name_var_type,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_var] = anon_sym_var,
  [anon_sym__] = anon_sym__,
  [sym_term_break] = sym_term_break,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [sym_term_continue] = sym_term_continue,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_return] = anon_sym_return,
  [sym_type_spec_simple] = sym_type_spec_simple,
  [sym_ROOT] = sym_ROOT,
  [sym_annotated_item] = sym_annotated_item,
  [sym_attribute] = sym_attribute,
  [sym_attributes] = sym_attributes,
  [sym__expr] = sym__expr,
  [sym__ident] = sym__ident,
  [sym__ident_lower_scoped] = sym__ident_lower_scoped,
  [sym_ident_scope] = sym_ident_scope,
  [sym_item] = sym_item,
  [sym_item_import] = sym_item_import,
  [sym__item_function] = sym__item_function,
  [sym_item_function_extern] = sym_item_function_extern,
  [sym_item_function_normal] = sym_item_function_normal,
  [sym__literal_bool] = sym__literal_bool,
  [sym_literal_map] = sym_literal_map,
  [sym_literal_vec] = sym_literal_vec,
  [sym_module_alias] = sym_module_alias,
  [sym_module_path] = sym_module_path,
  [sym_name] = sym_name,
  [sym_name_arg] = sym_name_arg,
  [sym_name_func] = sym_name_func,
  [sym_name_var_term] = sym_name_var_term,
  [sym__term] = sym__term,
  [sym_term_cond] = sym_term_cond,
  [sym_term_decl_var] = sym_term_decl_var,
  [sym_term_for] = sym_term_for,
  [sym__term_literal] = sym__term_literal,
  [sym_term_return] = sym_term_return,
  [sym_term_wildcard] = sym_term_wildcard,
  [aux_sym_ROOT_repeat1] = aux_sym_ROOT_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
  [aux_sym_ident_scope_repeat1] = aux_sym_ident_scope_repeat1,
  [aux_sym_item_function_extern_repeat1] = aux_sym_item_function_extern_repeat1,
  [aux_sym_literal_map_repeat1] = aux_sym_literal_map_repeat1,
  [aux_sym_literal_vec_repeat1] = aux_sym_literal_vec_repeat1,
  [aux_sym_module_path_repeat1] = aux_sym_module_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__ident_lower] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__ident_upper] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__item_relation] = {
    .visible = false,
    .named = true,
  },
  [sym_item_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_item_typedef] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_bool_false] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_bool_true] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_name_var_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_term_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_term_continue] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_type_spec_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_ROOT] = {
    .visible = true,
    .named = true,
  },
  [sym_annotated_item] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym__ident_lower_scoped] = {
    .visible = false,
    .named = true,
  },
  [sym_ident_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_item_import] = {
    .visible = true,
    .named = true,
  },
  [sym__item_function] = {
    .visible = false,
    .named = true,
  },
  [sym_item_function_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_item_function_normal] = {
    .visible = true,
    .named = true,
  },
  [sym__literal_bool] = {
    .visible = false,
    .named = true,
  },
  [sym_literal_map] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_vec] = {
    .visible = true,
    .named = true,
  },
  [sym_module_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_module_path] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_name_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_name_func] = {
    .visible = true,
    .named = true,
  },
  [sym_name_var_term] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_term_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_term_decl_var] = {
    .visible = true,
    .named = true,
  },
  [sym_term_for] = {
    .visible = true,
    .named = true,
  },
  [sym__term_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_term_return] = {
    .visible = true,
    .named = true,
  },
  [sym_term_wildcard] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_ROOT_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ident_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_function_extern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_vec_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(10);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(11);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(14);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '[') ADVANCE(9);
      END_STATE();
    case 5:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(23);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__ident_lower);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__ident_upper);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_name_var_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'b') ADVANCE(3);
      if (lookahead == 'c') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead == 'm') ADVANCE(9);
      if (lookahead == 'r') ADVANCE(10);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead == 'v') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'm') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead == 'y') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 46:
      if (lookahead == 'k') ADVANCE(59);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 53:
      if (lookahead == '_') ADVANCE(65);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 55:
      if (lookahead == 'h') ADVANCE(67);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_literal_bool_true);
      END_STATE();
    case 58:
      if (lookahead == '_') ADVANCE(69);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_term_break);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(70);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_literal_bool_false);
      END_STATE();
    case 63:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 65:
      if (lookahead == 'r') ADVANCE(74);
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 66:
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 69:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(79);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 72:
      if (lookahead == 'o') ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(81);
      if (lookahead == 'u') ADVANCE(82);
      END_STATE();
    case 75:
      if (lookahead == 'y') ADVANCE(83);
      END_STATE();
    case 76:
      if (lookahead == 'l') ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 78:
      if (lookahead == 'p') ADVANCE(85);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(87);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(88);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(89);
      END_STATE();
    case 83:
      if (lookahead == 'p') ADVANCE(90);
      END_STATE();
    case 84:
      if (lookahead == '_') ADVANCE(91);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_term_continue);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 91:
      if (lookahead == 'i') ADVANCE(96);
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 92:
      if (lookahead == 'c') ADVANCE(98);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_item_rule);
      END_STATE();
    case 95:
      if (lookahead == 'd') ADVANCE(100);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 97:
      if (lookahead == 't') ADVANCE(102);
      END_STATE();
    case 98:
      if (lookahead == '_') ADVANCE(103);
      END_STATE();
    case 99:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 100:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 101:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 103:
      if (lookahead == 's') ADVANCE(108);
      END_STATE();
    case 104:
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 105:
      if (lookahead == 'f') ADVANCE(110);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_literal_int);
      END_STATE();
    case 107:
      if (lookahead == 'i') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 'i') ADVANCE(112);
      END_STATE();
    case 109:
      if (lookahead == 'n') ADVANCE(113);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_item_typedef);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(114);
      END_STATE();
    case 112:
      if (lookahead == 'm') ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym__item_relation);
      END_STATE();
    case 114:
      if (lookahead == 'g') ADVANCE(116);
      END_STATE();
    case 115:
      if (lookahead == 'p') ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_literal_string);
      END_STATE();
    case 117:
      if (lookahead == 'l') ADVANCE(118);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_type_spec_simple);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 6},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 6},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 2},
  [156] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__ident_lower] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym__ident_upper] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__item_relation] = ACTIONS(1),
    [sym_item_rule] = ACTIONS(1),
    [sym_item_typedef] = ACTIONS(1),
    [sym_literal_bool_false] = ACTIONS(1),
    [sym_literal_bool_true] = ACTIONS(1),
    [sym_literal_int] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_literal_string] = ACTIONS(1),
    [sym_name_var_type] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_term_break] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_term_continue] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_type_spec_simple] = ACTIONS(1),
  },
  [1] = {
    [sym_ROOT] = STATE(145),
    [sym_annotated_item] = STATE(46),
    [sym_attributes] = STATE(53),
    [sym_item] = STATE(65),
    [sym_item_import] = STATE(64),
    [sym__item_function] = STATE(64),
    [sym_item_function_extern] = STATE(64),
    [sym_item_function_normal] = STATE(64),
    [aux_sym_ROOT_repeat1] = STATE(46),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND_LBRACK] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_function] = ACTIONS(11),
    [sym__item_relation] = ACTIONS(13),
    [sym_item_rule] = ACTIONS(13),
    [sym_item_typedef] = ACTIONS(13),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(29), 1,
      anon_sym_else,
    ACTIONS(31), 1,
      anon_sym_for,
    ACTIONS(33), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(19), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    ACTIONS(17), 5,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    STATE(39), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [54] = 11,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(19), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    ACTIONS(17), 5,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
    STATE(39), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [105] = 11,
    ACTIONS(29), 1,
      anon_sym_else,
    ACTIONS(41), 1,
      sym__ident_lower,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 1,
      anon_sym_var,
    ACTIONS(53), 1,
      anon_sym__,
    ACTIONS(56), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      anon_sym_for,
    ACTIONS(62), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(44), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(39), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [152] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(65), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(147), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [196] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(67), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(119), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [240] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(69), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(144), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [284] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(71), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(140), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [328] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(73), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(122), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [372] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(75), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(134), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [416] = 10,
    ACTIONS(41), 1,
      sym__ident_lower,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 1,
      anon_sym_var,
    ACTIONS(53), 1,
      anon_sym__,
    ACTIONS(77), 1,
      anon_sym_if,
    ACTIONS(80), 1,
      anon_sym_for,
    ACTIONS(83), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(44), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(39), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [460] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(86), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(77), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [504] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(88), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(105), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [548] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(90), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(107), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [592] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(92), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(104), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [636] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(94), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(127), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [680] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(96), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(133), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [724] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(98), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(78), 11,
      sym__expr,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [768] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(31), 1,
      anon_sym_for,
    ACTIONS(33), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(100), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(70), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [811] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(102), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(23), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [854] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(110), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(19), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [897] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(112), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(45), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [940] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(31), 1,
      anon_sym_for,
    ACTIONS(33), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(114), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(72), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [983] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(112), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(45), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1026] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(118), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_for,
    ACTIONS(122), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(116), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(43), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1069] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(118), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_for,
    ACTIONS(122), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(124), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(48), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1112] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(31), 1,
      anon_sym_for,
    ACTIONS(33), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(112), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(45), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1155] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(118), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_for,
    ACTIONS(122), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(112), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(45), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1198] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(31), 1,
      anon_sym_for,
    ACTIONS(33), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(116), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(43), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1241] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(118), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_for,
    ACTIONS(122), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(126), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(49), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1284] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(128), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(30), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1327] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(37), 1,
      anon_sym_for,
    ACTIONS(39), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(116), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(43), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1370] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(116), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(43), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1413] = 10,
    ACTIONS(15), 1,
      sym__ident_lower,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym__,
    ACTIONS(104), 1,
      anon_sym_if,
    ACTIONS(106), 1,
      anon_sym_for,
    ACTIONS(108), 1,
      anon_sym_return,
    STATE(42), 1,
      sym_name_var_term,
    ACTIONS(130), 4,
      sym_literal_bool_false,
      sym_literal_bool_true,
      sym_term_break,
      sym_term_continue,
    STATE(26), 10,
      sym__literal_bool,
      sym_literal_map,
      sym_literal_vec,
      sym__term,
      sym_term_cond,
      sym_term_decl_var,
      sym_term_for,
      sym__term_literal,
      sym_term_return,
      sym_term_wildcard,
  [1456] = 2,
    ACTIONS(134), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(132), 12,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_in,
      anon_sym_return,
  [1479] = 2,
    ACTIONS(138), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(136), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1501] = 2,
    ACTIONS(142), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(140), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1523] = 2,
    ACTIONS(146), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(144), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1545] = 2,
    ACTIONS(150), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(148), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1567] = 2,
    ACTIONS(154), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(152), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1589] = 2,
    ACTIONS(158), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(156), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1611] = 2,
    ACTIONS(162), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(160), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1633] = 2,
    ACTIONS(166), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(164), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1655] = 2,
    ACTIONS(170), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(168), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1677] = 2,
    ACTIONS(174), 6,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH_GT,
    ACTIONS(172), 11,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      anon_sym_else,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1699] = 10,
    ACTIONS(5), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_extern,
    ACTIONS(11), 1,
      anon_sym_function,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_attributes,
    STATE(65), 1,
      sym_item,
    STATE(47), 2,
      sym_annotated_item,
      aux_sym_ROOT_repeat1,
    ACTIONS(13), 3,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
    STATE(64), 4,
      sym_item_import,
      sym__item_function,
      sym_item_function_extern,
      sym_item_function_normal,
  [1736] = 10,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(183), 1,
      anon_sym_import,
    ACTIONS(186), 1,
      anon_sym_extern,
    ACTIONS(189), 1,
      anon_sym_function,
    STATE(53), 1,
      sym_attributes,
    STATE(65), 1,
      sym_item,
    STATE(47), 2,
      sym_annotated_item,
      aux_sym_ROOT_repeat1,
    ACTIONS(192), 3,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
    STATE(64), 4,
      sym_item_import,
      sym__item_function,
      sym_item_function_extern,
      sym_item_function_normal,
  [1773] = 3,
    ACTIONS(197), 1,
      anon_sym_LBRACK,
    ACTIONS(199), 1,
      anon_sym_else,
    ACTIONS(195), 10,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1792] = 3,
    ACTIONS(197), 1,
      anon_sym_LBRACK,
    ACTIONS(202), 1,
      anon_sym_else,
    ACTIONS(195), 10,
      sym__ident_lower,
      sym_literal_bool_false,
      sym_literal_bool_true,
      anon_sym_var,
      anon_sym__,
      sym_term_break,
      anon_sym_if,
      sym_term_continue,
      anon_sym_for,
      anon_sym_return,
  [1811] = 3,
    ACTIONS(206), 1,
      anon_sym_COLON_COLON,
    STATE(51), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(204), 9,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_as,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1829] = 3,
    ACTIONS(206), 1,
      anon_sym_COLON_COLON,
    STATE(52), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(208), 9,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_as,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1847] = 3,
    ACTIONS(212), 1,
      anon_sym_COLON_COLON,
    STATE(52), 1,
      aux_sym_module_path_repeat1,
    ACTIONS(210), 9,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_as,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1865] = 6,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_extern,
    ACTIONS(11), 1,
      anon_sym_function,
    STATE(66), 1,
      sym_item,
    ACTIONS(13), 3,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
    STATE(64), 4,
      sym_item_import,
      sym__item_function,
      sym_item_function_extern,
      sym_item_function_normal,
  [1889] = 1,
    ACTIONS(210), 10,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_import,
      anon_sym_as,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1902] = 2,
    ACTIONS(217), 1,
      anon_sym_as,
    ACTIONS(215), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1916] = 1,
    ACTIONS(219), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1927] = 1,
    ACTIONS(221), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1938] = 1,
    ACTIONS(223), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1949] = 1,
    ACTIONS(225), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1960] = 1,
    ACTIONS(227), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1971] = 1,
    ACTIONS(229), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1982] = 1,
    ACTIONS(231), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [1993] = 1,
    ACTIONS(233), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2004] = 1,
    ACTIONS(235), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2015] = 1,
    ACTIONS(237), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2026] = 1,
    ACTIONS(239), 8,
      ts_builtin_sym_end,
      anon_sym_POUND_LBRACK,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2037] = 7,
    ACTIONS(241), 1,
      sym__ident_lower,
    ACTIONS(243), 1,
      sym__ident_upper,
    STATE(74), 1,
      aux_sym_ident_scope_repeat1,
    STATE(136), 1,
      sym_name_func,
    STATE(137), 1,
      sym_ident_scope,
    STATE(138), 1,
      sym__ident_lower_scoped,
    STATE(139), 1,
      sym__ident,
  [2059] = 7,
    ACTIONS(241), 1,
      sym__ident_lower,
    ACTIONS(243), 1,
      sym__ident_upper,
    STATE(74), 1,
      aux_sym_ident_scope_repeat1,
    STATE(131), 1,
      sym_name_func,
    STATE(137), 1,
      sym_ident_scope,
    STATE(138), 1,
      sym__ident_lower_scoped,
    STATE(139), 1,
      sym__ident,
  [2081] = 1,
    ACTIONS(245), 6,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2090] = 2,
    ACTIONS(247), 1,
      anon_sym_else,
    ACTIONS(197), 5,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
  [2101] = 1,
    ACTIONS(250), 6,
      anon_sym_import,
      anon_sym_extern,
      anon_sym_function,
      sym__item_relation,
      sym_item_rule,
      sym_item_typedef,
  [2110] = 2,
    ACTIONS(252), 1,
      anon_sym_else,
    ACTIONS(197), 5,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
  [2121] = 3,
    STATE(73), 1,
      aux_sym_ident_scope_repeat1,
    STATE(139), 1,
      sym__ident,
    ACTIONS(254), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2132] = 3,
    STATE(73), 1,
      aux_sym_ident_scope_repeat1,
    STATE(139), 1,
      sym__ident,
    ACTIONS(243), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2143] = 3,
    STATE(50), 1,
      sym__ident,
    STATE(55), 1,
      sym_module_path,
    ACTIONS(257), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2154] = 3,
    STATE(58), 1,
      sym_module_alias,
    STATE(62), 1,
      sym__ident,
    ACTIONS(259), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2165] = 4,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RBRACK,
    ACTIONS(265), 1,
      anon_sym_DASH_GT,
    STATE(85), 1,
      aux_sym_literal_vec_repeat1,
  [2178] = 3,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_literal_map_repeat1,
  [2188] = 3,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      aux_sym_attributes_repeat1,
  [2198] = 3,
    ACTIONS(276), 1,
      sym__ident_lower,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(114), 1,
      sym_name_arg,
  [2208] = 3,
    ACTIONS(280), 1,
      sym__ident_lower,
    STATE(89), 1,
      sym_attribute,
    STATE(141), 1,
      sym_name,
  [2218] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_item_function_extern_repeat1,
  [2228] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_item_function_extern_repeat1,
  [2238] = 3,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RBRACK,
    STATE(84), 1,
      aux_sym_literal_map_repeat1,
  [2248] = 3,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_literal_vec_repeat1,
  [2258] = 3,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_literal_vec_repeat1,
  [2268] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_item_function_extern_repeat1,
  [2278] = 3,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_item_function_extern_repeat1,
  [2288] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RBRACK,
    STATE(93), 1,
      aux_sym_attributes_repeat1,
  [2298] = 3,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RBRACK,
    STATE(84), 1,
      aux_sym_literal_map_repeat1,
  [2308] = 3,
    ACTIONS(276), 1,
      sym__ident_lower,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      sym_name_arg,
  [2318] = 3,
    ACTIONS(280), 1,
      sym__ident_lower,
    STATE(98), 1,
      sym_attribute,
    STATE(141), 1,
      sym_name,
  [2328] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      aux_sym_attributes_repeat1,
  [2338] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_item_function_extern_repeat1,
  [2348] = 2,
    STATE(54), 1,
      sym__ident,
    ACTIONS(319), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2356] = 1,
    ACTIONS(321), 2,
      sym__ident_lower,
      sym__ident_upper,
  [2361] = 2,
    ACTIONS(323), 1,
      anon_sym_COLON_COLON,
    ACTIONS(325), 1,
      anon_sym_LPAREN,
  [2368] = 1,
    ACTIONS(274), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2373] = 2,
    ACTIONS(327), 1,
      sym__ident_lower,
    STATE(146), 1,
      sym_name_var_term,
  [2380] = 2,
    ACTIONS(327), 1,
      sym__ident_lower,
    STATE(148), 1,
      sym_name_var_term,
  [2387] = 2,
    ACTIONS(276), 1,
      sym__ident_lower,
    STATE(110), 1,
      sym_name_arg,
  [2394] = 2,
    ACTIONS(327), 1,
      sym__ident_lower,
    STATE(153), 1,
      sym_name_var_term,
  [2401] = 2,
    ACTIONS(327), 1,
      sym__ident_lower,
    STATE(44), 1,
      sym_name_var_term,
  [2408] = 1,
    ACTIONS(329), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2413] = 1,
    ACTIONS(298), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2418] = 1,
    ACTIONS(331), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2423] = 1,
    ACTIONS(333), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2428] = 2,
    ACTIONS(327), 1,
      sym__ident_lower,
    STATE(142), 1,
      sym_name_var_term,
  [2435] = 1,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
  [2439] = 1,
    ACTIONS(337), 1,
      anon_sym_COLON,
  [2443] = 1,
    ACTIONS(339), 1,
      sym_type_spec_simple,
  [2447] = 1,
    ACTIONS(341), 1,
      anon_sym_LBRACE,
  [2451] = 1,
    ACTIONS(343), 1,
      sym_type_spec_simple,
  [2455] = 1,
    ACTIONS(345), 1,
      anon_sym_COLON,
  [2459] = 1,
    ACTIONS(347), 1,
      anon_sym_COLON,
  [2463] = 1,
    ACTIONS(349), 1,
      sym_type_spec_simple,
  [2467] = 1,
    ACTIONS(351), 1,
      anon_sym_COLON,
  [2471] = 1,
    ACTIONS(353), 1,
      anon_sym_COLON,
  [2475] = 1,
    ACTIONS(355), 1,
      anon_sym_RBRACE,
  [2479] = 1,
    ACTIONS(357), 1,
      anon_sym_COLON,
  [2483] = 1,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [2487] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
  [2491] = 1,
    ACTIONS(363), 1,
      anon_sym_COLON,
  [2495] = 1,
    ACTIONS(365), 1,
      anon_sym_LPAREN,
  [2499] = 1,
    ACTIONS(367), 1,
      sym_type_spec_simple,
  [2503] = 1,
    ACTIONS(369), 1,
      sym_type_spec_simple,
  [2507] = 1,
    ACTIONS(371), 1,
      anon_sym_DASH_GT,
  [2511] = 1,
    ACTIONS(373), 1,
      anon_sym_COLON,
  [2515] = 1,
    ACTIONS(375), 1,
      anon_sym_LPAREN,
  [2519] = 1,
    ACTIONS(377), 1,
      sym_type_spec_simple,
  [2523] = 1,
    ACTIONS(379), 1,
      anon_sym_LPAREN,
  [2527] = 1,
    ACTIONS(381), 1,
      sym_type_spec_simple,
  [2531] = 1,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
  [2535] = 1,
    ACTIONS(385), 1,
      anon_sym_RBRACE,
  [2539] = 1,
    ACTIONS(387), 1,
      anon_sym_COLON,
  [2543] = 1,
    ACTIONS(389), 1,
      anon_sym_LPAREN,
  [2547] = 1,
    ACTIONS(391), 1,
      sym__ident_lower,
  [2551] = 1,
    ACTIONS(393), 1,
      anon_sym_LPAREN,
  [2555] = 1,
    ACTIONS(395), 1,
      anon_sym_COLON_COLON,
  [2559] = 1,
    ACTIONS(397), 1,
      anon_sym_RPAREN,
  [2563] = 1,
    ACTIONS(399), 1,
      anon_sym_EQ,
  [2567] = 1,
    ACTIONS(401), 1,
      anon_sym_in,
  [2571] = 1,
    ACTIONS(403), 1,
      anon_sym_EQ,
  [2575] = 1,
    ACTIONS(405), 1,
      anon_sym_RPAREN,
  [2579] = 1,
    ACTIONS(407), 1,
      ts_builtin_sym_end,
  [2583] = 1,
    ACTIONS(409), 1,
      anon_sym_in,
  [2587] = 1,
    ACTIONS(411), 1,
      anon_sym_RPAREN,
  [2591] = 1,
    ACTIONS(413), 1,
      anon_sym_in,
  [2595] = 1,
    ACTIONS(415), 1,
      sym_type_spec_simple,
  [2599] = 1,
    ACTIONS(417), 1,
      anon_sym_function,
  [2603] = 1,
    ACTIONS(419), 1,
      sym_type_spec_simple,
  [2607] = 1,
    ACTIONS(421), 1,
      anon_sym_LPAREN,
  [2611] = 1,
    ACTIONS(423), 1,
      anon_sym_in,
  [2615] = 1,
    ACTIONS(425), 1,
      anon_sym_LPAREN,
  [2619] = 1,
    ACTIONS(427), 1,
      anon_sym_COLON,
  [2623] = 1,
    ACTIONS(429), 1,
      anon_sym_LPAREN,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 105,
  [SMALL_STATE(5)] = 152,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 240,
  [SMALL_STATE(8)] = 284,
  [SMALL_STATE(9)] = 328,
  [SMALL_STATE(10)] = 372,
  [SMALL_STATE(11)] = 416,
  [SMALL_STATE(12)] = 460,
  [SMALL_STATE(13)] = 504,
  [SMALL_STATE(14)] = 548,
  [SMALL_STATE(15)] = 592,
  [SMALL_STATE(16)] = 636,
  [SMALL_STATE(17)] = 680,
  [SMALL_STATE(18)] = 724,
  [SMALL_STATE(19)] = 768,
  [SMALL_STATE(20)] = 811,
  [SMALL_STATE(21)] = 854,
  [SMALL_STATE(22)] = 897,
  [SMALL_STATE(23)] = 940,
  [SMALL_STATE(24)] = 983,
  [SMALL_STATE(25)] = 1026,
  [SMALL_STATE(26)] = 1069,
  [SMALL_STATE(27)] = 1112,
  [SMALL_STATE(28)] = 1155,
  [SMALL_STATE(29)] = 1198,
  [SMALL_STATE(30)] = 1241,
  [SMALL_STATE(31)] = 1284,
  [SMALL_STATE(32)] = 1327,
  [SMALL_STATE(33)] = 1370,
  [SMALL_STATE(34)] = 1413,
  [SMALL_STATE(35)] = 1456,
  [SMALL_STATE(36)] = 1479,
  [SMALL_STATE(37)] = 1501,
  [SMALL_STATE(38)] = 1523,
  [SMALL_STATE(39)] = 1545,
  [SMALL_STATE(40)] = 1567,
  [SMALL_STATE(41)] = 1589,
  [SMALL_STATE(42)] = 1611,
  [SMALL_STATE(43)] = 1633,
  [SMALL_STATE(44)] = 1655,
  [SMALL_STATE(45)] = 1677,
  [SMALL_STATE(46)] = 1699,
  [SMALL_STATE(47)] = 1736,
  [SMALL_STATE(48)] = 1773,
  [SMALL_STATE(49)] = 1792,
  [SMALL_STATE(50)] = 1811,
  [SMALL_STATE(51)] = 1829,
  [SMALL_STATE(52)] = 1847,
  [SMALL_STATE(53)] = 1865,
  [SMALL_STATE(54)] = 1889,
  [SMALL_STATE(55)] = 1902,
  [SMALL_STATE(56)] = 1916,
  [SMALL_STATE(57)] = 1927,
  [SMALL_STATE(58)] = 1938,
  [SMALL_STATE(59)] = 1949,
  [SMALL_STATE(60)] = 1960,
  [SMALL_STATE(61)] = 1971,
  [SMALL_STATE(62)] = 1982,
  [SMALL_STATE(63)] = 1993,
  [SMALL_STATE(64)] = 2004,
  [SMALL_STATE(65)] = 2015,
  [SMALL_STATE(66)] = 2026,
  [SMALL_STATE(67)] = 2037,
  [SMALL_STATE(68)] = 2059,
  [SMALL_STATE(69)] = 2081,
  [SMALL_STATE(70)] = 2090,
  [SMALL_STATE(71)] = 2101,
  [SMALL_STATE(72)] = 2110,
  [SMALL_STATE(73)] = 2121,
  [SMALL_STATE(74)] = 2132,
  [SMALL_STATE(75)] = 2143,
  [SMALL_STATE(76)] = 2154,
  [SMALL_STATE(77)] = 2165,
  [SMALL_STATE(78)] = 2178,
  [SMALL_STATE(79)] = 2188,
  [SMALL_STATE(80)] = 2198,
  [SMALL_STATE(81)] = 2208,
  [SMALL_STATE(82)] = 2218,
  [SMALL_STATE(83)] = 2228,
  [SMALL_STATE(84)] = 2238,
  [SMALL_STATE(85)] = 2248,
  [SMALL_STATE(86)] = 2258,
  [SMALL_STATE(87)] = 2268,
  [SMALL_STATE(88)] = 2278,
  [SMALL_STATE(89)] = 2288,
  [SMALL_STATE(90)] = 2298,
  [SMALL_STATE(91)] = 2308,
  [SMALL_STATE(92)] = 2318,
  [SMALL_STATE(93)] = 2328,
  [SMALL_STATE(94)] = 2338,
  [SMALL_STATE(95)] = 2348,
  [SMALL_STATE(96)] = 2356,
  [SMALL_STATE(97)] = 2361,
  [SMALL_STATE(98)] = 2368,
  [SMALL_STATE(99)] = 2373,
  [SMALL_STATE(100)] = 2380,
  [SMALL_STATE(101)] = 2387,
  [SMALL_STATE(102)] = 2394,
  [SMALL_STATE(103)] = 2401,
  [SMALL_STATE(104)] = 2408,
  [SMALL_STATE(105)] = 2413,
  [SMALL_STATE(106)] = 2418,
  [SMALL_STATE(107)] = 2423,
  [SMALL_STATE(108)] = 2428,
  [SMALL_STATE(109)] = 2435,
  [SMALL_STATE(110)] = 2439,
  [SMALL_STATE(111)] = 2443,
  [SMALL_STATE(112)] = 2447,
  [SMALL_STATE(113)] = 2451,
  [SMALL_STATE(114)] = 2455,
  [SMALL_STATE(115)] = 2459,
  [SMALL_STATE(116)] = 2463,
  [SMALL_STATE(117)] = 2467,
  [SMALL_STATE(118)] = 2471,
  [SMALL_STATE(119)] = 2475,
  [SMALL_STATE(120)] = 2479,
  [SMALL_STATE(121)] = 2483,
  [SMALL_STATE(122)] = 2487,
  [SMALL_STATE(123)] = 2491,
  [SMALL_STATE(124)] = 2495,
  [SMALL_STATE(125)] = 2499,
  [SMALL_STATE(126)] = 2503,
  [SMALL_STATE(127)] = 2507,
  [SMALL_STATE(128)] = 2511,
  [SMALL_STATE(129)] = 2515,
  [SMALL_STATE(130)] = 2519,
  [SMALL_STATE(131)] = 2523,
  [SMALL_STATE(132)] = 2527,
  [SMALL_STATE(133)] = 2531,
  [SMALL_STATE(134)] = 2535,
  [SMALL_STATE(135)] = 2539,
  [SMALL_STATE(136)] = 2543,
  [SMALL_STATE(137)] = 2547,
  [SMALL_STATE(138)] = 2551,
  [SMALL_STATE(139)] = 2555,
  [SMALL_STATE(140)] = 2559,
  [SMALL_STATE(141)] = 2563,
  [SMALL_STATE(142)] = 2567,
  [SMALL_STATE(143)] = 2571,
  [SMALL_STATE(144)] = 2575,
  [SMALL_STATE(145)] = 2579,
  [SMALL_STATE(146)] = 2583,
  [SMALL_STATE(147)] = 2587,
  [SMALL_STATE(148)] = 2591,
  [SMALL_STATE(149)] = 2595,
  [SMALL_STATE(150)] = 2599,
  [SMALL_STATE(151)] = 2603,
  [SMALL_STATE(152)] = 2607,
  [SMALL_STATE(153)] = 2611,
  [SMALL_STATE(154)] = 2615,
  [SMALL_STATE(155)] = 2619,
  [SMALL_STATE(156)] = 2623,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ROOT, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_return, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_return, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(156),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(35),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(39),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_term_return, 1), SHIFT(12),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(103),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(40),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(34),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(154),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(4),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(31),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(152),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_return, 1), SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(154),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name_var_term, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_var_term, 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_vec, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_vec, 4),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_map, 5),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_map, 5),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_vec, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_vec, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_return, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_return, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_wildcard, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_wildcard, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_map, 6),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_map, 6),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_decl_var, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_decl_var, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_for, 7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_for, 7),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_decl_var, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_decl_var, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_cond, 5),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_cond, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ROOT, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2), SHIFT_REPEAT(81),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2), SHIFT_REPEAT(75),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2), SHIFT_REPEAT(150),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2), SHIFT_REPEAT(67),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ROOT_repeat1, 2), SHIFT_REPEAT(64),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_cond, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_cond, 3),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term_cond, 3), SHIFT(28),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2), SHIFT_REPEAT(95),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_import, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_extern, 10),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_extern, 7),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_import, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_normal, 12),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_extern, 11),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_normal, 13),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_alias, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_function_normal, 9),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated_item, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotated_item, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_term_cond, 3), SHIFT(27),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ident_scope_repeat1, 2), SHIFT_REPEAT(139),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2), SHIFT_REPEAT(92),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_literal_map_repeat1, 2), SHIFT_REPEAT(16),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_literal_map_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_literal_vec_repeat1, 2), SHIFT_REPEAT(13),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_literal_vec_repeat1, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_function_extern_repeat1, 2), SHIFT_REPEAT(101),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_function_extern_repeat1, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ident_scope_repeat1, 2),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident, 1),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_lower_scoped, 1),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_function_extern_repeat1, 4),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_literal_map_repeat1, 4),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_arg, 1),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident_lower_scoped, 2),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_func, 1),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [407] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ddlog_dl(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__ident_lower,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
